export const UniversalGrey: string;
export const RentBlue: string;
export const Gray3: string;
export const Counter: string;
export const Label: string;
export const Counter_Controls: string;
export const Text: string;
export const Counter_Button: string;
export const Counter_ButtonIcon: string;
