export const Gray1: string;
export const Gray2: string;
export const Gray3: string;
export const Header: string;
export const Group: string;
export const Icon_box: string;
export const Icon: string;
export const Icon_text: string;
export const Row: string;
