export const Gray2: string;
export const RentBlue: string;
export const UniversalGrey: string;
export const FilterPanel: string;
export const FilterPanel_Header: string;
export const FilterPanel_Footer: string;
export const FilterPanel_Header_CancelButton: string;
export const FilterPanel_Header_FilterText: string;
export const Form: string;
