export layer from './layer.svg'
export location from './location.svg'
export mapMarker from './mapMarker.svg'
export mapPoi from './mapPoi.svg'
export zoomIn from './zoomIn.svg'
export zoomOut from './zoomOut.svg'
