export const RentBlue: string;
export const RatingSummary: string;
export const RatingSummary_Prefix: string;
export const RatingSummary_Item: string;
export const RatingBar_Icons: string;
export const RatingBar_Background: string;
export const RatingBar: string;
export const Label: string;
export const RatingSummary_Star: string;
