export Icon from './Icon'

// UNUSED ICONS // Please only export ones that will actually be used.
// export amenities from './svgs/amenities/amenities.svg'
// export bathroom from './svgs/amenities/bathroom.svg'
// export bedroom from './svgs/amenities/bedroom.svg'
// export apartment from './svgs/apartment.svg'
// export avatar from './svgs/avatar.svg'
// export arrowDown from './svgs/arrowDown.svg'
// export arrowUp from './svgs/arrowUp.svg'
// export back from './svgs/back.svg'
// export bicycle from './svgs/bicycle.svg'
// export car from './svgs/car.svg'
// export check from './svgs/check.svg'
// export crime from './svgs/crime.svg'
// export favorite from './svgs/favorite.svg'
// export unfavorite from './svgs/unfavorite.svg'
// export flag from './svgs/flag.svg'
// export floorplan from './svgs/floorplan.svg'
// export fullscreen from './svgs/fullscreen.svg'
// export fullscreenExit from './svgs/fullscreenExit.svg'
// export heart from './svgs/heart.svg'
// export heartEmpty from './svgs/heartEmpty.svg'
// export hood from './svgs/hood.svg'
// export house from './svgs/house.svg'
// export park from './svgs/park.svg'
// export pencil from './svgs/pencil.svg'
// export phone from './svgs/phone.svg'
// export phoneOutline from './svgs/phoneOutline.svg'
// export refresh from './svgs/refresh.svg'
// export schoolBook from './svgs/schoolBook.svg'
// export schools from './svgs/schools.svg'
// export transport from './svgs/transport.svg'
// export trash from './svgs/trash.svg'
// export vert from './svgs/vert.svg'
// export view from './svgs/view.svg'
// export walk from './svgs/walk.svg'
// export forward from './svgs/forward.svg'
