export PinIcon from './map-pin.png'
export InactivePinIcon from './map-pin-inactive.png'
export SelectedPinIcon from './map-pin-selected.png'
export TeardropIcon from './map-teardrop.png'
export PdpPinLogoIcon from './pdp-pin-logo.png'
