export const RentBlue: string;
export const UniversalGrey: string;
export const Gray3: string;
export const Red: string;
export const MoveInDate_Container: string;
export const MoveInDate_Calendar: string;
export const MoveInDate_DateField: string;
export const ValidatedField_CheckMarkIcon: string;
export const MoveInDateClickArea: string;
