export const Gray1: string;
export const SeoLinkList_Container: string;
export const SeoLinkList_Collapsible: string;
export const SeoLinkList_CollapsibleToggle: string;
export const SeoLinkList_Content: string;
export const SeoLinkList_Content_Left: string;
export const SeoLinkList_Content_Right: string;
export const SeoLinkList_LinkGroup: string;
export const SeoLinkList_Header: string;
