export const UniversalGrey: string;
export const RentBlue: string;
export const Gray1: string;
export const Gray3: string;
export const Gray5: string;
export const SortFilters_ChevronDown: string;
export const SortFilters_Dropdown: string;
export const SortFilters_Text: string;
export const FiltersButton_ButtonPrefix: string;
